alias: Запросить счет за электроэнергию
description: ""
triggers:
  - trigger: time
    at: "01:00:00"
conditions:
  - condition: template
    value_template: "{{ now().day == 5 }}"
actions:
  - action: tns_energo.get_bill
    data:
      device_id: <YOUR_DEVICE_ID>
mode: single
