alias: Уведомление о счете за электроэнергию
description: ""
triggers:
  - trigger: event
    event_type: tns_energo_get_bill_completed
conditions: []
actions:
  # отправка PDF в Telegram
  - action: telegram_bot.send_document
    data:
      file: "{{ trigger.event.data.file_path }}"
      caption: >-
        ⚡Счет за электроэнергию для
        {{device_attr(trigger.event.data.device_id, 'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name')}}
        за {{ trigger.event.data.date }}
  # уведомление в веб-интерфейсе со ссылкой на скачивание
  - action: persistent_notification.create
    data:
      title: >-
        ⚡Счет за электроэнергию для
        {{device_attr(trigger.event.data.device_id, 'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name')}}
        за {{ trigger.event.data.date }}
      message: >-
        <a href="{{ trigger.event.data.url }}" target="_blank">Скачать счет</a>
mode: single
