alias: Уведомление об ошибке ТНС-Энерго
description: ""
triggers:
  - trigger: event
    event_type: tns_energo_send_readings_failed
  - trigger: event
    event_type: tns_energo_get_bill_failed
  - trigger: event
    event_type: tns_energo_refresh_failed
conditions: []
actions:
  # уведомление в Telegram
  - action: notify.send_message
    target:
      entity_id: <YOUR_NOTIFY_ENTITY>
    data:
      title: >-
        {% if trigger.event.event_type == 'tns_energo_send_readings_failed' %}
        Ошибка при передаче показаний для
        {% elif trigger.event.event_type == 'tns_energo_get_bill_failed' %}
        Ошибка при получении счета для
        {% elif trigger.event.event_type == 'tns_energo_refresh_failed' %}
        Ошибка при обновлении информации для
        {% else %}
        Ошибка при выполнении действия для
        {% endif %}
        {{device_attr(trigger.event.data.device_id, 'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name')}}
        от {{ now().strftime('%d.%m.%Y %H:%M')}}
      message: "{{ trigger.event.data.error }}"
  # уведомление в веб-интерфейсе
  - action: persistent_notification.create
    data:
      title: >-
        {% if trigger.event.event_type == 'tns_energo_send_readings_failed' %}
        Ошибка при передаче показаний для
        {% elif trigger.event.event_type == 'tns_energo_get_bill_failed' %}
        Ошибка при получении счета для
        {% elif trigger.event.event_type == 'tns_energo_refresh_failed' %}
        Ошибка при обновлении информации для
        {% else %}
        Ошибка при выполнении действия для
        {% endif %}
        {{device_attr(trigger.event.data.device_id, 'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name')}}
        от {{ now().strftime('%d.%m.%Y %H:%M')}}
      message: "{{ trigger.event.data.error }}"
mode: single
