alias: Уведомление об отправленных показаниях
description: ""
triggers:
  - trigger: event
    event_type: tns_energo_send_readings_completed
conditions: []
actions:
  # уведомление в Telegram
  - action: notify.send_message
    target:
      entity_id: <YOUR_NOTIFY_ENTITY>
    data:
      title: >-
        ⚡Показания для
        {{device_attr(trigger.event.data.device_id, 'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name')}}
        отправлены {{ now().strftime('%d.%m.%Y %H:%M')}}
      message: >-
        Показания: {{ trigger.event.data.readings | join(', ') }} кВт⋅ч
  # уведомление в веб-интерфейсе
  - action: persistent_notification.create
    data:
      title: >-
        ⚡Показания для
        {{device_attr(trigger.event.data.device_id, 'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name')}}
        отправлены {{ now().strftime('%d.%m.%Y %H:%M')}}
      message: >-
        Показания: {{ trigger.event.data.readings | join(', ') }} кВт⋅ч
mode: single
